<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Message;
use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findyAllSendMessageByLoggedUser($userSend)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM AppBundle:Message m 
            WHERE m.sender = :userSend ORDER BY m.createdAt DESC')
            ->setParameter('userSend', $userSend)
            ->getResult();
    }

    public function findAllReceiveredMessageByLoggedUser($userReceived)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM AppBundle:Message m 
            WHERE m.receiver = :userReceived ORDER BY m.createdAt DESC')
            ->setParameter('userReceived', $userReceived)
            ->getResult();

    }
}
