<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Message;
use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findyAllSendMessageByLoggedUser($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM AppBundle:Message m 
            WHERE m.sender = :id ORDER BY m.createdAt DESC')
            ->setParameter('id', $id)
            ->getResult();
    }

    public function findAllReceiveredMessageByLoggedUser($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m FROM AppBundle:Message m 
            WHERE m.receiver = :id ORDER BY m.createdAt DESC')
            ->setParameter('id', $id)
            ->getResult();

    }
}
